### ISSUE TITLE
wooden fence door

### ISSUE THREAD

**Issue by taberenc** [taberenc/AOG_2022#4]
Is required a door in the wooden fence in the farm of Clairia, in order to let the player to have a better access to Clairia bees.
That's needed because they are the ones who give honey.

**Comment by Novae17** [comment]
I can take care of that now, I still have some time left today~

**Comment by Novae17** [comment]
I fixed the issue and will do a pull request to fix it from my branch.

**Comment by taberenc** [comment]
ok.. i'll check it out later

**Comment by taberenc** [comment]
fence door issue closed by now, by the addition of wooden boxes and capability to jump over them.
